version: '3.8'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: airtribe

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
